import SearchBar from "@/components/searchbar/SearchBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-full flex flex-col justify-between">
      <div className="mb-5">{children}</div>
      <div className="w-full sticky z-50 bottom-8 flex justify-between bg-white dark:bg-neutral-950">
        <SearchBar />
      </div>
    </div>
  );
}
