import SearchBar from "@/components/searchbar/SearchBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-full flex flex-col justify-between">
      {children}
      <div className="sticky bottom-8">
        <SearchBar />
      </div>
    </div>
  );
}
